require("dotenv").config();
const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
  title: String,
  slug: { type: String, unique: true },
  img: String,
  price: Number,
  discount: Number,
  category: String,
  type: String,
  brand: String,
  description: String,
  rating: Number,
  quantity: Number,
}, { timestamps: true });

const Product = mongoose.model("Product", productSchema);

const products = [
  {
    title: "Hydrating Face Cream",
    slug: "hydrating-face-cream",
    img: "/assets/img/product/product-1.jpg",
    price: 29.99,
    discount: 10,
    category: "skincare",
    type: "beauty",
    brand: "Shofy",
    description: "A lightweight daily moisturizer for soft, hydrated skin.",
    rating: 4.5,
    quantity: 100,
  },
  {
    title: "Velvet Matte Lipstick",
    slug: "velvet-matte-lipstick",
    img: "/assets/img/product/product-2.jpg",
    price: 18.99,
    discount: 0,
    category: "makeup",
    type: "cosmetics",
    brand: "Shofy",
    description: "Long-lasting color with a comfortable matte finish.",
    rating: 4.2,
    quantity: 75,
  },
  {
    title: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    img: "/assets/img/product/product-3.jpg",
    price: 34.99,
    discount: 15,
    category: "skincare",
    type: "beauty",
    brand: "Glow Lab",
    description: "A lightweight serum that helps skin look brighter and more even.",
    rating: 4.8,
    quantity: 60,
  },
  {
    title: "Overnight Repair Mask",
    slug: "overnight-repair-mask",
    img: "/assets/img/product/product-4.jpg",
    price: 26.5,
    discount: 5,
    category: "skincare",
    type: "beauty",
    brand: "Pure Form",
    description: "A nourishing night mask for a soft, rested-looking complexion.",
    rating: 4.6,
    quantity: 48,
  },
  {
    title: "Rose Water Face Mist",
    slug: "rose-water-face-mist",
    img: "/assets/img/product/product-5.jpg",
    price: 14.99,
    discount: 0,
    category: "skincare",
    type: "beauty",
    brand: "Shofy",
    description: "A refreshing mist to hydrate and revive skin throughout the day.",
    rating: 4.3,
    quantity: 120,
  },
  {
    title: "Silk Finish Foundation",
    slug: "silk-finish-foundation",
    img: "/assets/img/product/product-6.jpg",
    price: 31.99,
    discount: 10,
    category: "makeup",
    type: "cosmetics",
    brand: "Lustre",
    description: "Buildable medium coverage with a comfortable natural finish.",
    rating: 4.5,
    quantity: 85,
  },
  {
    title: "Cloud Glow Blush",
    slug: "cloud-glow-blush",
    img: "/assets/img/product/product-7.jpg",
    price: 16.99,
    discount: 0,
    category: "makeup",
    type: "cosmetics",
    brand: "Lustre",
    description: "A silky powder blush that blends easily for a fresh flush of color.",
    rating: 4.4,
    quantity: 70,
  },
  {
    title: "Everyday Eye Palette",
    slug: "everyday-eye-palette",
    img: "/assets/img/product/product-8.jpg",
    price: 28.0,
    discount: 20,
    category: "makeup",
    type: "cosmetics",
    brand: "Shofy",
    description: "A versatile palette of blendable shades for day and evening looks.",
    rating: 4.7,
    quantity: 42,
  },
  {
    title: "Nourishing Lip Oil",
    slug: "nourishing-lip-oil",
    img: "/assets/img/product/product-9.jpg",
    price: 12.99,
    discount: 5,
    category: "makeup",
    type: "cosmetics",
    brand: "Glow Lab",
    description: "A glossy, nourishing lip oil with a cushion-soft feel.",
    rating: 4.1,
    quantity: 95,
  },
  {
    title: "Relaxed Linen Overshirt",
    slug: "relaxed-linen-overshirt",
    img: "/assets/img/product/product-10.jpg",
    price: 54.99,
    discount: 15,
    category: "mens-fashion",
    type: "fashion",
    brand: "Northline",
    description: "A breathable linen layer made for easy everyday styling.",
    rating: 4.5,
    quantity: 35,
  },
  {
    title: "Everyday Leather Tote",
    slug: "everyday-leather-tote",
    img: "/assets/img/product/product-11.jpg",
    price: 72.0,
    discount: 10,
    category: "accessories",
    type: "fashion",
    brand: "Atelier 9",
    description: "A structured tote with room for daily essentials and a laptop.",
    rating: 4.8,
    quantity: 24,
  },
  {
    title: "Soft Knit Weekend Set",
    slug: "soft-knit-weekend-set",
    img: "/assets/img/product/product-12.jpg",
    price: 64.5,
    discount: 20,
    category: "womens-fashion",
    type: "fashion",
    brand: "Northline",
    description: "A soft knit co-ordinated set for comfortable off-duty days.",
    rating: 4.4,
    quantity: 30,
  },
  {
    title: "Minimal Leather Sneakers",
    slug: "minimal-leather-sneakers",
    img: "/assets/img/product/product-13.jpg",
    price: 88.0,
    discount: 0,
    category: "footwear",
    type: "fashion",
    brand: "Atelier 9",
    description: "Clean leather sneakers with a cushioned sole for all-day wear.",
    rating: 4.6,
    quantity: 40,
  },
  {
    title: "Noise Canceling Headphones",
    slug: "noise-canceling-headphones",
    img: "/assets/img/product/product-14.jpg",
    price: 129.99,
    discount: 12,
    category: "audio",
    type: "electronics",
    brand: "Echo One",
    description: "Comfortable wireless headphones with focused, immersive sound.",
    rating: 4.7,
    quantity: 28,
  },
  {
    title: "Compact Smart Watch",
    slug: "compact-smart-watch",
    img: "/assets/img/product/product-15.jpg",
    price: 99.0,
    discount: 10,
    category: "wearables",
    type: "electronics",
    brand: "Pulse",
    description: "A slim smart watch for daily activity, messages, and wellness tracking.",
    rating: 4.3,
    quantity: 32,
  },
  {
    title: "Portable Desk Speaker",
    slug: "portable-desk-speaker",
    img: "/assets/img/product/product-16.jpg",
    price: 45.0,
    discount: 5,
    category: "audio",
    type: "electronics",
    brand: "Echo One",
    description: "A compact Bluetooth speaker with warm sound for work or home.",
    rating: 4.2,
    quantity: 55,
  },
  {
    title: "Wireless Charging Stand",
    slug: "wireless-charging-stand",
    img: "/assets/img/product/product-17.jpg",
    price: 29.5,
    discount: 0,
    category: "mobile-accessories",
    type: "electronics",
    brand: "Pulse",
    description: "A tidy charging stand that keeps your phone visible while it powers up.",
    rating: 4.1,
    quantity: 80,
  },
];

const additionalProducts = [
  ["Men's Classic Jeans", "mens-classic-jeans", "mens-jeans", "fashion", 49.99, "Northline"],
  ["Men's Slim Fit Trouser", "mens-slim-fit-trouser", "mens-trouser", "fashion", 42.0, "Northline"],
  ["Men's Casual Pants", "mens-casual-pants", "mens-pants", "fashion", 39.99, "Urban Thread"],
  ["Men's Active Joggers", "mens-active-joggers", "mens-joggers", "fashion", 34.99, "Urban Thread"],
  ["Men's Oxford Shirt", "mens-oxford-shirt", "mens-shirt", "fashion", 44.5, "Northline"],
  ["Men's Everyday T-Shirt", "mens-everyday-tshirt", "mens-tshirts", "fashion", 19.99, "Urban Thread"],
  ["Men's Comfort Undergarments", "mens-comfort-undergarments", "mens-undergarments", "fashion", 16.99, "Daily Form"],
  ["Women's Straight Jeans", "womens-straight-jeans", "womens-jeans", "fashion", 52.99, "Atelier 9"],
  ["Women's Tailored Trouser", "womens-tailored-trouser", "womens-trouser", "fashion", 48.0, "Atelier 9"],
  ["Women's Relaxed Pants", "womens-relaxed-pants", "womens-pants", "fashion", 45.5, "Northline"],
  ["Women's Lounge Joggers", "womens-lounge-joggers", "womens-joggers", "fashion", 32.99, "Daily Form"],
  ["Women's Satin Shirt", "womens-satin-shirt", "womens-shirt", "fashion", 38.99, "Atelier 9"],
  ["Women's Essential T-Shirt", "womens-essential-tshirt", "womens-tshirts", "fashion", 18.5, "Daily Form"],
  ["Women's Soft Undergarments", "womens-soft-undergarments", "womens-undergarments", "fashion", 21.99, "Daily Form"],
  ["Kids Classic Jeans", "kids-classic-jeans", "kids-jeans", "fashion", 29.99, "Little North"],
  ["Kids Smart Trouser", "kids-smart-trouser", "kids-trouser", "fashion", 27.5, "Little North"],
  ["Kids Easy Pants", "kids-easy-pants", "kids-pants", "fashion", 24.99, "Little North"],
  ["Kids Play Joggers", "kids-play-joggers", "kids-joggers", "fashion", 22.99, "Tiny Motion"],
  ["Kids Cotton Shirt", "kids-cotton-shirt", "kids-shirt", "fashion", 23.5, "Little North"],
  ["Kids Graphic T-Shirt", "kids-graphic-tshirt", "kids-tshirts", "fashion", 14.99, "Tiny Motion"],
  ["Kids Everyday Undergarments", "kids-everyday-undergarments", "kids-undergarments", "fashion", 13.99, "Tiny Motion"],
  ["Everyday 5G Smartphone", "everyday-5g-smartphone", "mobile", "electronics", 399.99, "Pulse"],
  ["4K Smart Television", "4k-smart-television", "tv", "electronics", 599.0, "Vision One"],
  ["Ultra Portable Laptop", "ultra-portable-laptop", "laptops", "electronics", 749.99, "Pulse"],
  ["Family Android Tablet", "family-android-tablet", "tablets", "electronics", 229.99, "Vision One"],
  ["Compact Mirrorless Camera", "compact-mirrorless-camera", "cameras", "electronics", 679.0, "Vision One"],
  ["Fast USB-C Power Bank", "fast-usb-c-power-bank", "mobile-accessories", "electronics", 39.99, "Pulse"],
].map(([title, slug, category, type, price, brand], index) => ({
  title,
  slug,
  img: `/assets/img/product/product-${(index % 17) + 1}.jpg`,
  price,
  discount: index % 3 === 0 ? 10 : 0,
  category,
  type,
  brand,
  description: `A thoughtfully designed ${title.toLowerCase()} for everyday use.`,
  rating: Number((4.1 + (index % 8) / 10).toFixed(1)),
  quantity: 25 + (index * 7) % 80,
}));

products.push(...additionalProducts);

mongoose.connect(process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/shofy", {
  serverSelectionTimeoutMS: 5000,
})
  .then(async () => {
    await Product.deleteMany({});
    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);
    await mongoose.disconnect();
  })
  .catch((error) => {
    console.error(`MongoDB connection failed: ${error.message}`);
    console.error("Start MongoDB or set MONGODB_URI in backend/.env, then run npm run seed again.");
    process.exit(1);
  });
